### PR TITLE
Allow running from crontab

### PR DESCRIPTION
**Pull request by barbudor**
Disable `-it` argument on `docker run` if no standard input is provided (== no tty)
This allows automated builds such as from crontab

### CODE REVIEW

**Comment by barbudor** [comment]
Hi @blakadder 
Was is intended that your merge removed my previous PR which introduced the shell variable `DOCKER_IMAGE` ?
Thanks

**Comment by blakadder** [comment]
No, I just clicked resolve conflict and deleted two old lines with -it

**Comment by barbudor** [comment]
If your OK, I will make another PR to recreate TASMOTA_DOCKER_IMAGE allowing it to be specified outside of the script. Would be much more convenient this way.
Thanks

**Comment by blakadder** [comment]
of course i'm ok

**Pull request merged**
